# Generated by Django 3.1 on 2020-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Disp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('imag', models.ImageField(upload_to='men/images/')),
            ],
        ),
    ]
