# Generated by Django 3.1 on 2020-09-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('imag', models.ImageField(upload_to='men/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Display3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('imag', models.ImageField(upload_to='men/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Dis',
        ),
        migrations.DeleteModel(
            name='Disp',
        ),
    ]
